name: API build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**/*'

jobs:
  web-release:
    name: Build & Deploy API
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '11'

      - name: Build
        run: mvn install

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: './target'
          files: |
            spring-boot-ecommerce-0.0.1-SNAPSHOT.jar/
            captain-definition
            Dockerfile
          outPath: /github/workspace/deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
